### ISSUE TITLE
I really need your help

### ISSUE THREAD

**Issue by howard9779** [xincoder/GRIP#3] opened 2020-08-24 14:58 UTC
hello Im using your code but I got some problems like this could you give me some help? thx

**Comment by howard9779** [comment] 2020-08-24 15:00
Launching pytest with arguments C:/Users/howard/Desktop/GRIP-master/main.py in C:\Users\howard\Desktop\GRIP-master

============================= test session starts =============================
platform win32 -- Python 3.7.1, pytest-4.0.2, py-1.7.0, pluggy-0.8.0 -- C:\Users\howard\Anaconda3\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\howard\Desktop\GRIP-master, inifile:
plugins: remotedata-0.3.1, openfiles-0.3.1, doctestplus-0.2.0, arraydiff-0.3
collecting ... collected 1 item

main.py::test_model ERROR                                                [100%]
test setup failed
file C:\Users\howard\Desktop\GRIP-master\main.py, line 264
  def test_model(pra_model, pra_data_loader):
E       fixture 'pra_model' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_xml_attribute, record_xml_property, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

C:\Users\howard\Desktop\GRIP-master\main.py:264


=================================== ERRORS ====================================
________________________ ERROR at setup of test_model _________________________
file C:\Users\howard\Desktop\GRIP-master\main.py, line 264
  def test_model(pra_model, pra_data_loader):
E       fixture 'pra_model' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_xml_attribute, record_xml_property, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

C:\Users\howard\Desktop\GRIP-master\main.py:264
=========================== 1 error in 0.59 seconds ===========================

Process finished with exit code 1

Assertion failed

Assertion failed

**Comment by howard9779** [comment] 2020-08-24 15:01
I really need some help for this ,please. and sorry for my poor english

**Comment by xincoder** [comment] 2020-08-24 17:41
Hi @howard9779, it seems like the error caused by the environment. Would you please try to reset your environment. I suggest using Anaconda. You should not face any problem if you run the code directly in a common PyTorch environment. (pytest is not an expected package.)

**Comment by howard9779** [comment] 2020-08-25 11:54
thank you for your reply and device I will try it again.謝謝您的回覆,我參考了您的論文,其實有蠻多問題想跟您請教的,不知道是否方便有聯絡方式呢?

**Comment by xincoder** [comment] 2020-08-25 19:58
Hi @howard9779, we are chatting offline. Thus, I will close this issue.

**Closed as completed by xincoder** 2020-08-25 19:58 UTC
